In [1]:
def success():
    print("sucess")
    print("incoming")
success()    

sucess
incoming


function overloading

In [12]:
def numerical(arg):
    for i in arg:
        if(not(isinstance(i,(int,float)))):
            return False
    return True

In [9]:
numerical([5,8,0,2.3])

True

#Strings

In [152]:
a="String josfp"
print(a[5:])
print(a[-9:])
print(a[2:9])
print(a[-9:-2:2])

g josfp
ing josfp
ring jo
igjs


In [147]:
def rotateStr(n):
    for i in range(len(n)):
        print(n[i:len(n)]+n[-len(n):-len(n)+i])

In [148]:
rotatestr("aman")

aman
mana
anam
nama


In [153]:
a[1]="u"
#s rttring immutable

TypeError: 'str' object does not support item assignment

In [154]:
a[::-1]

'pfsoj gnirtS'

In [157]:
str="67"
str2="6op"
print(int(str))
print(int(str2))

67


ValueError: invalid literal for int() with base 10: '6op'

In [172]:
s="  asdfd    fDgH;ggFGg;hGD  "

In [173]:
s.strip()

'asdfd    fDgH;ggFGg;hGD'

In [174]:
s.upper()

'  ASDFD    FDGH;GGFGG;HGD  '

In [175]:
s.lower()

'  asdfd    fdgh;ggfgg;hgd  '

In [176]:
s.replace(" ",",")

',,asdfd,,,,fDgH;ggFGg;hGD,,'

In [177]:
s.split(";")

['  asdfd    fDgH', 'ggFGg', 'hGD  ']

In [178]:
s.islower()

False

In [181]:
# s. tab to see string func
len(s)

27

In [184]:
sum([7,78,89])

174

In [185]:
ss="aman at home"

In [186]:
"man" in ss

True

In [187]:
"man" not in ss 

False

In [189]:
"aman"=="Aman"

False

In [195]:
"mam"<"Man"


False

In [197]:
"man"<"nan"

True

Data Struct

In [198]:
#list  ordered,changeable,duplicates
#tuple ordered,unchangeable,duplicates
#set   unordered,removeable/addable,no duplicates
#dict  unordered,changeable,no duplicates



In [265]:
l=[1.2,13,9.9,"name"]
t=(1.3,8,9.9,"name")
s={1,74,74,"name",7.6}
d={22:"ayushi",31:"aman","college":"gbu","college":"iiitg"}

In [246]:
print("list:",l)
print("tupple:",t)
print("set:",s)
print("dict:",d)

list: [1.2, 13, 9.9, 'name']
tupple: (1.3, 8, 9.9, 'name')
set: {1, 74, 7.6, 'name'}
dict: {22: 'ayushi', 31: 'aman', 'college': 'iiitg'}


In [247]:
print(l[2])
print(t[1])
print(74 in s)
print(d[22])

9.9
8
True
ayushi


In [248]:
print(l[::-1])#reverses the list

['name', 9.9, 13, 1.2]


In [249]:
print(s[::-1])

TypeError: 'set' object is not subscriptable

In [250]:
print(t[::-1])

('name', 9.9, 8, 1.3)


In [251]:
t1=(1,2)
t2=(3,2)
t3=t1+t2

In [252]:
t3

(1, 2, 3, 2)

In [253]:
t4=t3
t4 

(1, 2, 3, 2)

s.remove("74")

In [266]:
s.remove("name")
s
s.Remove(7.6)
s

AttributeError: 'set' object has no attribute 'Remove'

In [267]:
del d["college"]
d

{22: 'ayushi', 31: 'aman'}

In [270]:
d1={"a":"aman"}
d2={"s":"shivani"}
#d1=d1+d2 will not concat
d1.update(d2)
d1

{'a': 'aman', 's': 'shivani'}

In [286]:
l=[4,3453,2.3,656]
l3=l  #l and l3 repressenting same memory ##call by reference
l2=l.copy() #l2 represents different memory but same elements as l ##call bye value
l2[1]=98
l3[1]=65
print(l3)
print(l2)
print(l)

[4, 65, 2.3, 656]
[4, 98, 2.3, 656]
[4, 65, 2.3, 656]


In [287]:
#slicing i is saved as copy
L=l[:3]
L

[4, 65, 2.3]

In [288]:
L[1]=59874
print(l)
L

[4, 65, 2.3, 656]


[4, 59874, 2.3]

In [289]:
#l.clear()

In [290]:
l

[4, 65, 2.3, 656]

In [291]:
D={"list":l,'set':s}

In [300]:
print(D['list'][1],"of",D['list'])

65 of [4, 65, 2.3, 656]


In [295]:
D['set']

{1, 7.6, 74}

In [314]:
import numpy as np
a=np.array([4,7,90,4])
b=a.copy() # 1.b=a.copy() 2.b=a 
print(a,b)
b[0]=5
print(b)
print(a)
print(type(a))


[ 4  7 90  4] [ 4  7 90  4]
[ 5  7 90  4]
[ 4  7 90  4]
<class 'numpy.ndarray'>


In [316]:
a.dtype

dtype('int64')

In [357]:
d=np.array(([[98,89,45.5],[54,54,78]],[[65,43,32],[65,7,43]]),dtype='f')

In [358]:
d

array([[[98. , 89. , 45.5],
        [54. , 54. , 78. ]],

       [[65. , 43. , 32. ],
        [65. ,  7. , 43. ]]], dtype=float32)

In [359]:
d.ndim

3

In [360]:
d[1,1,2]

43.0

In [361]:
d.shape


(2, 2, 3)

In [362]:
B=np.array(3) # not array
B.ndim

0

In [363]:
d.size

12

In [364]:
f=np.arange(20,55,5)

In [365]:
f

array([20, 25, 30, 35, 40, 45, 50])

In [366]:
print(range(10))
print(list(range(10)))

range(0, 10)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [370]:
np.random.permutation(list(range(10)))

array([2, 4, 6, 0, 7, 8, 9, 1, 5, 3])

In [371]:
np.random.randint(10,50,10)

array([17, 46, 29, 35, 33, 18, 23, 48, 14, 11])

In [387]:
print(np.random.randint(10,50))
print(np.random.rand(1,2))

40
[[0.18421317 0.77951763]]


In [373]:
np.random.randint?


In [375]:
A=np.random.randint(10,50,10)
A

array([36, 12, 10, 30, 32, 33, 26, 40, 31, 31])

In [383]:
A.reshape(2,5) #reshape(row,column)

array([[36, 12, 10, 30, 32],
       [33, 26, 40, 31, 31]])